# .github/workflows/ci.yml
name: CI  # This is the display name of your workflow

# “on:” tells GitHub when to trigger this workflow:
on:
  push:
    branches:
      - main            # → Run whenever you push to the “main” branch
  pull_request:
    branches:
      - main            # → Also run when a PR targets “main”

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest  # Use a fresh Ubuntu runner

    steps:
      # Step 1: Check out your repository onto the runner
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python 3.x on the runner
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # Step 3: Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Step 4: Run your script (adjust the “run:” line as needed)
      - name: Run log_analyzer help
        run: |
          # Example: verify that “log_analyzer.py --help” returns exit code 0
          python log_analyzer.py --help
